-- Журнал согласий и версии принятых документов (152-ФЗ)
ALTER TABLE users ADD COLUMN IF NOT EXISTS pd_consent_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pd_consent_version VARCHAR(32);
ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_version VARCHAR(32);

CREATE TABLE IF NOT EXISTS user_consent_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    consent_type    VARCHAR(32)  NOT NULL,
    policy_version  VARCHAR(32)  NOT NULL,
    ip_address      VARCHAR(45),
    user_agent      VARCHAR(512),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_consent_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_consent_log_user ON user_consent_log(user_id);
