CREATE TABLE IF NOT EXISTS game_saves (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL UNIQUE,
    state_json      TEXT         NOT NULL,
    player_name     VARCHAR(64),
    career_title    VARCHAR(64),
    company_name    VARCHAR(128),
    game_day        INT          NOT NULL DEFAULT 1,
    game_mode       VARCHAR(32),
    project_type    VARCHAR(64),
    game_over       BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_game_saves_user_id ON game_saves(user_id);
